export const prerender = true;

export function GET() {
  const content = [
    '# BitEvo Public Product Manifest',
    '',
    'BitEvo audits the action layer of AI-agent systems: what a workflow is allowed to change, what evidence must exist before it acts, how the external effect is confirmed, and how uncertainty is contained or recovered from.',
    '',
    '## BitEvo Doctrine',
    '- Authority Budget: every write permission, integration, autonomous step, retry path and approval shortcut expands the authority surface; capability does not automatically justify authority.',
    '- Evidence Before Effect: critical external effects should depend on evidence available at decision time; post-hoc logs can reconstruct an event but do not retroactively justify it.',
    '- False Green: an operational state that appears healthy or successful while required evidence is stale, missing, attached to the wrong object, or not independently confirmed at the external effect.',
    '',
    '## Decision-grade artifacts',
    '- Authority Ledger: critical action, target object, authority owner, approvals, allowed/prohibited transitions, replay rights and recovery ownership.',
    '- Evidence Contract: evidence required at decision time, provenance, freshness, object binding, approval evidence, version context, external confirmation and missing-evidence behavior.',
    '- Finding Record: trigger, authority involved, observed evidence, external effect, recovery behavior, reproduction, consequence and uncertainty.',
    '- Decision Memo: owner question, bounded decision, supporting evidence, residual uncertainty, required control change, resulting authority and retest criterion.',
    '',
    '## SAMPLE-001 public proof pack',
    '- /sample-audit is a synthetic worked example for one staging CRM qualification workflow.',
    '- /sample-audit.json exposes the same pack as machine-readable JSON.',
    '- SAMPLE-001 is explicitly NOT customer evidence, NOT an executed audit, NOT certification and NOT a universal safety score.',
    '- The pack demonstrates Authority Ledger -> Evidence Contract -> failure plan -> Finding Record -> Decision Memo -> retest criterion.',
    '- Provenance is kept visible: SYNTHETIC, ASSUMPTION, EXPECTED GATE and NOT TESTED are not presented as observations.',
    '',
    '## Local diagnostic',
    '- /diagnostic is a seven-gate local browser diagnostic for one workflow.',
    '- It returns unresolved decision gates rather than a numerical trust/safety score.',
    '- YES means a gate is explicitly described; NO/UNKNOWN means the gate remains unresolved and should be scoped or tested.',
    '- The diagnostic does not transmit data and does not certify a workflow.',
    '',
    '## Core audit model',
    '- Audit object: one concrete action-capable workflow, not an abstract model score.',
    '- Intent: what external change is being proposed, to which object, and for what reason.',
    '- Authority: what may act, on which object, under whose approval, and which transitions are prohibited.',
    '- Evidence: what must be present, fresh and attributable at decision time.',
    '- Effect: whether the intended external change is independently confirmed.',
    '- Recovery: how retries, interruption, stale state, partial effects and ambiguity are contained.',
    '- Owner decision: expand authority, constrain it, repair the workflow, or retest.',
    '',
    '## Primary service',
    'Agent Authority & Evidence Audit',
    '- Fixed price: USD 4,900',
    '- Duration: 5 working days',
    '- Scope: 1 staging/test workflow',
    '- Integrations: up to 3 tools / APIs / MCP servers',
    '- Failure plan: 10-20 agreed scenarios',
    '- Deliverables: Authority Ledger, Evidence Contract, reproducible Finding Records, Decision Memo/backlog and one retest',
    '',
    '## Commercial decision ladder',
    '- Free / 20 minutes: decide whether the workflow is worth auditing and identify the critical action, authority owner and staging boundary.',
    '- USD 1,500 Entry Audit: determine whether one primary failure hypothesis on one critical action chain is reproducible and decision-relevant.',
    '- USD 4,900 Primary Audit: decide whether one workflow has enough evidence, effect confirmation and recovery control for its current or proposed authority.',
    '- Hardening: quoted separately only after verified findings identify the real control gap.',
    '',
    '## Boundaries',
    'This is a bounded engineering audit. It is not certification, a universal AI safety score, legal advice, guaranteed security, guaranteed absence of defects, production penetration testing by default, or a profit promise.',
    'Written scope and Rules of Engagement are required before testing.',
    'Do not submit API keys, passwords, tokens, private keys, wallet seeds, production credentials, or customer secrets through public forms.',
    '',
    '## Canonical public routes',
    '- /',
    '- /doctrine',
    '- /artifacts',
    '- /sample-audit',
    '- /diagnostic',
    '- /agent-authority-audit',
    '- /audit-intake',
    '- /pricing',
    '- /consulting',
    '- /continuityos',
    '- /guides',
    '- /universe',
    '',
    '## Reviewed public research notes',
    '- /guides/ai-agent-reliability-audit',
    '- /guides/security-sandboxing',
    '- /guides/fleet-coordinator-drift-monitoring',
    '- /guides/d3-tool-io-bridge-contract',
    '',
    'Historical guide routes are not part of the reviewed public research set and may be redirected to /guides.',
    'This manifest intentionally contains no runtime telemetry, internal checkpoints, infrastructure identifiers, private operational state, credentials, or control endpoints.'
  ].join('\n');

  return new Response(content, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=300'
    }
  });
}
